-- migrate:up
create table if not exists  supacontent_projects (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name varchar check (char_length(name) > 3),
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table supacontent_projects enable row level security;
create policy "Individuals can create projects." on supacontent_projects for
    insert with check (auth.uid() = user_id);
create policy "Individuals can view their own projects. " on supacontent_projects for
    select using (auth.uid() = user_id);
create policy "Individuals can update their own projects." on supacontent_projects for
    update using (auth.uid() = user_id);
create policy "Individuals can delete their own projects." on supacontent_projects for
    delete using (auth.uid() = user_id);

-- migrate:down

-- drop table
drop table supacontent_projects cascade;
